#define FAIL { cerr<<"assertion failed on line "<<__LINE__<<endl; exit(123);}